; SMART HOME V1 - ESP32 đơn giản cho 1 Gateway
; Chỉ cần sửa thông tin trong include/CauHinh.h rồi nạp:
;   pio run -t upload
;   pio device monitor -b 115200

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
upload_speed = 921600

lib_deps =
  links2004/WebSockets @ ^2.6.1
  bblanchon/ArduinoJson @ ^6.21.5
